version: "3"

services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    image: ldw.solutions/site:latest
    container_name: ldw-site
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site.rule=Host(`ldw.solutions`)"
      - "traefik.http.routers.site.entrypoints=websecure"
      - "traefik.http.routers.site.tls.certresolver=ldwresolver"
    networks:
      - default
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
        reservations:
          cpus: "0.05"
          memory: 25M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

networks:
  default:
    external: true
    name: ldwsolutions
