version: "3"

services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    image: ldw.solutions/site:latest
    container_name: ldw-site
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site.rule=Host(`ldw.solutions`)"
      - "traefik.http.routers.site.entrypoints=websecure"
      - "traefik.http.routers.site.tls.certresolver=ldwresolver"
    networks:
      - default

networks:
  default:
    external: true
    name: ldwsolutions
